 # Index

- Concepts we look into
  > 
    - Indexing
    - Slicing 1d array
    - Slicing 2d array
    - Usage of step - such as arrange 
    - array of ones and zeros 
    - identity
    - Logical functions such as logical_and, logical_or
    - vectorization
    - broadcasting 2D array with a 1D array

# indexing 


We can access the elements of an array using its **index**. Index gives the location of an element of an array. 

- The first index is '0'.
- The second index is '1' and so on.
- The second last index is '-2'.
- The last index is '-1'.

### Indexing in a one-dimensional array

A one-dimensional array is indexed just like a list.

In [4]:
import numpy as np

a = np.array([10,55,23,44,25,89])

In [5]:
a[:]

array([10, 55, 23, 44, 25, 89])

In [6]:
a[1]

55

In [7]:
a[-1]

89

## Indexing 2-D array

In [8]:
a2 =np.array([[12,22,35],[15,61,69],[78,55,64]])
a2

array([[12, 22, 35],
       [15, 61, 69],
       [78, 55, 64]])

In [9]:
print(a2)

[[12 22 35]
 [15 61 69]
 [78 55 64]]


In [10]:
a2[1][2]

69

In [11]:
a2[1]

array([15, 61, 69])

In [12]:
   a2[1,2]

69

## Slicing
Slicing a single dimensional array 


In [13]:
a[:]

array([10, 55, 23, 44, 25, 89])

In [14]:
a[1:]


array([55, 23, 44, 25, 89])

In [15]:
a[-1:]

array([89])

In [16]:
a[:-1]

array([10, 55, 23, 44, 25])

In [17]:
a[2:4]

array([23, 44])

In [18]:
a[::2]

# "indexes with multiples of 2"

array([10, 23, 25])

In [19]:
a[::3]

array([10, 44])

### Slicing a two-dimensional array

You can slice a two-dimensional array in various ways:
- Print a row or a column
- Print multiple rows or columns
- Print a section of table for given rows and columns
- Print first and/or last rows and/or columns.
- Print rows and columns after certain step. 

Syntax: 
####  array_name [row start: row stop: row step], [col start, col stop, col step]

In [51]:
A = np.array([
["00", "01", "02", "03", "04"],
[10, 11, 12, 13, 14],
[20, 21, 22, 23, 24],
[30, 31, 32, 33, 34],
[40, 41, 42, 43, 44] 
])


In [61]:
A[1,:-2] # printing the row 


array(['10', '11', '12'], dtype='<U2')

In [22]:
A[:,2] # printing the column 

array(['02', '12', '22', '32', '42'], dtype='<U2')

Printing Multiple rows or columns 


In [23]:
A[:2,]

array([['00', '01', '02', '03', '04'],
       ['10', '11', '12', '13', '14']], dtype='<U2')

In [24]:
A[:,1:3]

array([['01', '02'],
       ['11', '12'],
       ['21', '22'],
       ['31', '32'],
       ['41', '42']], dtype='<U2')

In [25]:
# print first or last rows or columns 

print(A[0,])
print(A[:,-1])

['00' '01' '02' '03' '04']
['04' '14' '24' '34' '44']


In [26]:
#Print Selected rows and columns 

print(A[2:,2]) # print 3 rd row and second column 

['22' '32' '42']


In [27]:
print(A[3:,4]) # last column last two cells 

['34' '44']


In [28]:
# 1st three rows for the last three columns

print(A[:3,2:])

[['02' '03' '04']
 ['12' '13' '14']
 ['22' '23' '24']]


In [29]:
 # Array without last three columns

print(A[2:,2:])

[['22' '23' '24']
 ['32' '33' '34']
 ['42' '43' '44']]


In [30]:
# print first without last three columns

print(A[:,:-2])

[['00' '01' '02']
 ['10' '11' '12']
 ['20' '21' '22']
 ['30' '31' '32']
 ['40' '41' '42']]


## Using Step 

In [31]:
# Let us create a new array using the arange method for this exercise

# automatically create a 2 dimensional array with defined shape 

array = np.arange(50)
array.shape =(10,5) 
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [32]:
array.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [33]:
# Using step in slicing
print(array)
print(array[1::2,]) # Print rows 1, 3, and 5

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]
 [45 46 47 48 49]]


In [34]:
# Print columns 2 & 4

print(array[:,2::2])

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]
 [27 29]
 [32 34]
 [37 39]
 [42 44]
 [47 49]]


In [35]:
# This will print an intersection of elements of rows 0, 2, 4 and columns 0, 3

print(array[:5:2,:4:3])

[[ 0  3]
 [10 13]
 [20 23]]


## Array of ones and zeros

We will be initialising arrays which have all the elements either as zeros or one. Such arrays help us while performing arithmetic operations

In [36]:
o = np.ones((4,4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [37]:
o = np.ones((4,4),int).reshape(2,8)
print(o)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [38]:
z = np.zeros((4,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
z = np.zeros((4,4),int).reshape(2,8)
print(z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


Identity function 

having the diagnol identical 



In [40]:
I = np.identity(4)

print (I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
I = np.identity (3, dtype = int)

print (I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [42]:
np.logical_and
np.logical_or
np.newaxis
np.equal

<ufunc 'equal'>

## Vectorization

Vectorization of code helps us write complex codes in a compact way and execute them faster. 

It allows to **operate** or apply a function on a complex object, like an array, "at once" rather than iterating over the individual elements. NumPy supports vectorization in an efficient way.

In [43]:
import numpy as np # Start the notebook with importing the package

my_list = [1, 2, 3, 4, 5.5, 6.6, 7.123, 8.456]

V = np.array(my_list) # Creating a 1D array or vector

print (V)

[1.    2.    3.    4.    5.5   6.6   7.123 8.456]


#### Vectorization using scalars - addition

In [44]:
V_a = V + 2 # Every element is increased by 2.

print(V_a)

[ 3.     4.     5.     6.     7.5    8.6    9.123 10.456]


#### Vectorization using scalars - subtraction

In [45]:
V_s = V - 2.4 # Every element is reduced by 2.4.

print(V_s)

[-1.4   -0.4    0.6    1.6    3.1    4.2    4.723  6.056]


#### Vectorization using scalars - multiplication

In [46]:
V2 = np.array([ [1, 2, 3], [4,5,6], [7, 8, 9] ]) # Array of shape 3,3

V_m = V2 * 10 # Every element is multiplied by 10.

print(V2)
print(V_m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


### 2D Array operations with another 2D array

This is only possible when the shape of the two arrays is same. For example, a (2,2) array can be operated with another (2,2) array. 


In [63]:
A = np.array([ [1, 2, 3], [11, 22, 33], [111, 222, 333] ]) # Array of shape 3,3
B = np.ones ((3,3)) # Array of shape 3,3
C= np.ones ((4,4)) # Array of shape 4,4
print (A)
print (B)
print (C)

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### You can only ADD or SUB array with same dimensions 

In [65]:
# Addition of 2 arrays of same dimensions (3, 3)

print("Adding the arrays is element wise: ")

print(A + B)

Adding the arrays is element wise: 
[[  2.   3.   4.]
 [ 12.  23.  34.]
 [112. 223. 334.]]


In [69]:
# Addition of 2 arrays of different shapes or dimensions is NOT allowed

print("Addition of 2 arrays of different shapes or dimensions will throw a ValueError.")

print(A + C)

Addition of 2 arrays of different shapes or dimensions will throw a ValueError.


ValueError: operands could not be broadcast together with shapes (3,3) (4,4) 

In [70]:
# Subtraction of 2 arrays

print("Subtracting array B from A is element wise: ")

print(A - B)

Subtracting array B from A is element wise: 
[[  0.   1.   2.]
 [ 10.  21.  32.]
 [110. 221. 332.]]


In [71]:
# Multiplication of 2 arrays  

A1 = np.array([ [1, 2, 3], [4, 5, 6] ]) # Array of shape 2,3
A2 = np.array([ [1, 0, -1], [0, 1, -1] ]) # Array of shape 2,3

print("Array 1", A1)
print("Array 2", A2)
print("Multiplying two arrays: ", A1 * A2)
print("As you can see above, the multiplication happens element by element.")

Array 1 [[1 2 3]
 [4 5 6]]
Array 2 [[ 1  0 -1]
 [ 0  1 -1]]
Multiplying two arrays:  [[ 1  0 -3]
 [ 0  5 -6]]
As you can see above, the multiplication happens element by element.


Even Multiplication cant be done on different dimensions 

### Broadcasting allows 2D Array operations with a 1D array or vector

NumPy also supports broadcasting. Broadcasting allows us to combine objects of <b>different shapes</b> within a single operation.

But, do remember that to perform this operation one of the matrices needs to be a vector with its length equal to one of the dimensions of the other matrix.

In [72]:
import numpy as np

A = np.array([ [1, 2, 3], [11, 22, 33], [111, 222, 333] ])
B = np.array ([1,2,3])

print (A)
print (B)

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[1 2 3]


In [73]:
print( "Multiplication with broadcasting: " )

print (A * B)

Multiplication with broadcasting: 
[[  1   4   9]
 [ 11  44  99]
 [111 444 999]]


### Observation = Vectorisation can be done on 2-D and 1-D arrays but not on 2-d and 2-d arrays 

In [75]:
print( "... and now addition with broadcasting: " )

print (A + B)

... and now addition with broadcasting: 
[[  2   4   6]
 [ 12  24  36]
 [112 224 336]]


In [ ]:
# Try to understand the difference between the two 'B' arrays

B = np.array ([1, 2, 3] * 3)

print (B)

In [ ]:
B = np.array([[1, 2, 3],] * 3)

print(B)

# Hint: look at the brackets

In [ ]:
# Another example type

B = np.array([1, 2, 3])
B[:, np.newaxis]

# We have changed a row vector into a column vector

In [ ]:
A = np.linspace(1,10,50,False).reshape(5,10)

A

In [ ]:
print(np.shape(A[:,np.newaxis]))
np.shape(A)

In [ ]:
print(np.shape(B))
np.shape(B[:,np.newaxis])

In [ ]:
# This example should be self explanatory by now

A = np.array([10, 20, 30])
B = np.array([1, 2, 3])
A[:, np.newaxis]

In [ ]:
A[:, np.newaxis] * B

### Other operations

- Comparison operators: Comparing arrays and the elements of two similar shaped arrays
- Logical operators: AND/OR operands

In [ ]:

A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([ [11, 102, 13], [201, 22, 203], [31, 32, 303] ])

print (A)
print (B)

In [ ]:
A==B

In [ ]:
np.equal(A,B)

In [ ]:
np.array_equal(A,B)

### Logical operators

In [ ]:
# This should be self explanatory by now

a = np.array([ [True, True], [False, False]])
b = np.array([ [True, False], [True, False]])

print(np.logical_or(a, b))

In [ ]:
print(np.logical_and(a, b))

In [ ]:
print(a & b)
print(a | b)

In [ ]:
k =np.random.rand(2000,50)
print(k)

T = k/sum(k)
print(np.shape(T))
print(sum(T))
np.random.randn(2000,50)