# indexing 


We can access the elements of an array using its **index**. Index gives the location of an element of an array. 

- The first index is '0'.
- The second index is '1' and so on.
- The second last index is '-2'.
- The last index is '-1'.

### Indexing in a one-dimensional array

A one-dimensional array is indexed just like a list.

In [1]:
import numpy as np

a = np.array([10,55,23,44,25,89])

In [2]:
a[:]

array([10, 55, 23, 44, 25, 89])

In [3]:
a[1]

55

In [4]:
a[-1]

89

## Indexing 2-D array

In [8]:
a2 =np.array([[12,22,35],[15,61,69],[78,55,64]])
a2

array([[12, 22, 35],
       [15, 61, 69],
       [78, 55, 64]])

In [9]:
print(a2)

[[12 22 35]
 [15 61 69]
 [78 55 64]]


In [10]:
a2[1][2]

69

In [11]:
a2[1]

array([15, 61, 69])

In [12]:
   a2[1,2]

69

## Slicing
Slicing a single dimensional array 


In [14]:
a[:]

array([10, 55, 23, 44, 25, 89])

In [15]:
a[1:]


array([55, 23, 44, 25, 89])

In [16]:
a[-1:]

array([89])

In [17]:
a[:-1]

array([10, 55, 23, 44, 25])

In [18]:
a[2:4]

array([23, 44])

In [19]:
a[::2]

# "indexes with multiples of 2"

array([10, 23, 25])

In [20]:
a[::3]

array([10, 44])

### Slicing a two-dimensional array

You can slice a two-dimensional array in various ways:
- Print a row or a column
- Print multiple rows or columns
- Print a section of table for given rows and columns
- Print first and/or last rows and/or columns.
- Print rows and columns after certain step. 

Syntax: 
####  array_name [row start: row stop: row step], [col start, col stop, col step]

In [22]:
A = np.array([
["00", "01", "02", "03", "04"],
[10, 11, 12, 13, 14],
[20, 21, 22, 23, 24],
[30, 31, 32, 33, 34],
[40, 41, 42, 43, 44] 
])


In [27]:
A[1] # printing the row 

array(['10', '11', '12', '13', '14'], dtype='<U2')

In [29]:
A[:,2] # printing the column 

array(['02', '12', '22', '32', '42'], dtype='<U2')

Printing Multiple rows or columns 


In [30]:
A[:2,]

array([['00', '01', '02', '03', '04'],
       ['10', '11', '12', '13', '14']], dtype='<U2')

In [32]:
A[:,1:3]

array([['01', '02'],
       ['11', '12'],
       ['21', '22'],
       ['31', '32'],
       ['41', '42']], dtype='<U2')

In [34]:
# print first or last rows or columns 

print(A[0,])
print(A[:,-1])

['00' '01' '02' '03' '04']
['04' '14' '24' '34' '44']


In [37]:
#Print Selected rows and columns 

print(A[2:,2]) # print 3 rd row and second column 

['22' '32' '42']


In [39]:
print(A[3:,4]) # last column last two cells 

['34' '44']


In [40]:
# 1st three rows for the last three columns

print(A[:3,2:])

[['02' '03' '04']
 ['12' '13' '14']
 ['22' '23' '24']]


In [41]:
 # Array without last three columns

print(A[2:,2:])

[['22' '23' '24']
 ['32' '33' '34']
 ['42' '43' '44']]


In [42]:
# print first without last three columns

print(A[:,:-2])

[['00' '01' '02']
 ['10' '11' '12']
 ['20' '21' '22']
 ['30' '31' '32']
 ['40' '41' '42']]


## Using Step 

In [49]:
# Let us create a new array using the arange method for this exercise

# automatically create a 2 dimensional array with defined shape 

array = np.arange(50)
array.shape =(10,5) 
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [50]:
array.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
# Using step in slicing
print(array)
print(array[1::2,]) # Print rows 1, 3, and 5

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]
 [45 46 47 48 49]]


In [61]:
# Print columns 2 & 4

print(array[:,2::2])

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]
 [27 29]
 [32 34]
 [37 39]
 [42 44]
 [47 49]]


In [62]:
# This will print an intersection of elements of rows 0, 2, 4 and columns 0, 3

print(array[:5:2,:4:3])

[[ 0  3]
 [10 13]
 [20 23]]


## Array of ones and zeros

We will be initialising arrays which have all the elements either as zeros or one. Such arrays help us while performing arithmetic operations

In [65]:
o = np.ones((4,4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [70]:
o = np.ones((4,4),int).reshape(2,8)
print(o)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [71]:
z = np.zeros((4,4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [72]:
z = np.zeros((4,4),int).reshape(2,8)
print(z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


Identity function 

having the diagnol identical 



In [73]:
I = np.identity(4)

print (I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [74]:
I = np.identity (3, dtype = int)

print (I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [76]:
np.logical_and
np.logical_or
np.newaxis
np.equal

<ufunc 'equal'>