# Numpy or Numerical python 

*it is an acronym for numeric python or numerical python *

Numpy Provides two main things .

- It Providea fast precompiled functions for both mathematical and numerical routines 

- Powerful data structures such as multidimensional arrays and matrices and perfrom highlevel mathematical operations on them or with them.

`**An Array is a list of related values or same data types **`




#### List of this lecture 

- np.array()
- np.arange()
- np.linspace()
- np.shape()
- array.dtype
- array.ndim()


In [3]:
import numpy as np 


a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(a)

numpy.ndarray

In [6]:
a[1][0]

4

1) Array Help us to work on fundamental data frames  where in finance we will be using them a lot .

2) They also help us to perform operation on array at once rather than iterating over it . This in turn makes our programs very efficient and This is inturn called vectorification.

3) Array's help in broadcasting to combine objects of different shapes and within a single operation 

In [7]:
a = a*2.5

a

array([[ 2.5,  5. ,  7.5],
       [10. , 12.5, 15. ]])

In [8]:
a * a

array([[  6.25,  25.  ,  56.25],
       [100.  , 156.25, 225.  ]])

NumPy is the fundamental package for scientific computing with Python. It is an open source extension module for Python.

- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Useful linear algebra, Fourier transform, and random number capabilities
- Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data
- Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of database


## Converting lists or tuples into arrays 

In [9]:
mylist =[10,20,55,66,77]

array = np.array(mylist)
print(array)
type(array)

[10 20 55 66 77]


numpy.ndarray

In [10]:
list2 = [10,"ram","surya",30]

array2 = np.array(list2)
print(array2)
type(array2)

"""Intresting is that different data types list is also converted into array"""

['10' 'ram' 'surya' '30']


'Intresting is that different data types list is also converted into array'

In [11]:
stockvalues = (20.3, 25.3, 22.7, 19.0, 18.5, 21.2, 24.5, 26.6, 23.2, 21.2) # This is a tuple

array3 = np.array(stockvalues)
print(array3)
type(array3)

[20.3 25.3 22.7 19.  18.5 21.2 24.5 26.6 23.2 21.2]


numpy.ndarray

# Functions to create arrays quickly 

The above-discussed methods to create arrays require us to manually input the data points. To automatically create data points for an array we use these functions:

- arange
- linspace

**Both these functions create data points lying between two endpoints, starting and ending, so that they are evenly distributed. For example, we can create 50 data points lying between 1 and 10.*



### **arange**
Numpy.arange returns evenly spaced arrays by using a 'given' step or interval by the user.

Syntax:
####  arange ([start], [stop], [step], [dtype=None])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [14]:
np.arange(1,20,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5])

In [4]:
%%timeit
np.arange(1,20,0.5,int)



654 ns ± 6.32 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
# timeit
a = []
for i in range(20):
    a.append(i)   
print(a)
type(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


list

In [17]:
np.arange(1.3,23.3,2.1,int)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

### linspace

This function creates the array automatically just needs the number of elements hence it will create distance automatically which are equidistant .



Syntax:
#### linspace(start, stop, num=50, endpoint=True, retstep=False)

The 'start and the 'stop' determines the range of the array. 'num' determines the number of elements in the array. If the 'endpoint' is True, it will include the stop value and if it is false, the array will exclude the stop value.

If the optional parameter 'retstep' is set, the function will return the value of the spacing between adjacent values.

In [18]:
np.linspace(1,10,50)
# np.linspace?

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [42]:
k = np.linspace(1,10,50,True)
np.random.rand?

Docstring:
laplace(loc=0.0, scale=1.0, size=None)

Draw samples from the Laplace or double exponential distribution with
specified location (or mean) and scale (decay).

The Laplace distribution is similar to the Gaussian/normal distribution,
but is sharper at the peak and has fatter tails. It represents the
difference between two independent, identically distributed exponential
random variables.

.. note::
    New code should use the ``laplace`` method of a ``default_rng()``
    instance instead; see `random-quick-start`.

Parameters
----------
loc : float or array_like of floats, optional
    The position, :math:`\mu`, of the distribution peak. Default is 0.
scale : float or array_like of floats, optional
    :math:`\lambda`, the exponential decay. Default is 1. Must be non-
    negative.
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  If size is ``None`` (default),
    a single value is r

In [20]:
k1 = np.linspace(1,10,100,True,True)

type(k1)
k1 = np.array(k1)
type(k1)
k1

array([array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818

In [21]:
round(k1[1],2)

0.09

In [22]:
 np.linspace(1,10,50,False)

array([1.  , 1.18, 1.36, 1.54, 1.72, 1.9 , 2.08, 2.26, 2.44, 2.62, 2.8 ,
       2.98, 3.16, 3.34, 3.52, 3.7 , 3.88, 4.06, 4.24, 4.42, 4.6 , 4.78,
       4.96, 5.14, 5.32, 5.5 , 5.68, 5.86, 6.04, 6.22, 6.4 , 6.58, 6.76,
       6.94, 7.12, 7.3 , 7.48, 7.66, 7.84, 8.02, 8.2 , 8.38, 8.56, 8.74,
       8.92, 9.1 , 9.28, 9.46, 9.64, 9.82])

# dimensionality of arrays 

### zero dimensional arrays are scalars  

The above expamples are 1-D arrays and are also called vectors , currently scalar is only a single value .


In [23]:
p = np.array(50)
print("P:",p)

print("the dimension of a is ",np.ndim(a))

P: 50
the dimension of a is  1


### np.ndim(type array ) would return the dimension of an array 

In [24]:
print(type(p))
print(p.dtype)

<class 'numpy.ndarray'>
int32


ON a class of numpy array **dtype** function will return the datatype of the array 

In [25]:
array2.dtype

dtype('<U11')

In [26]:
array.dtype

dtype('int32')

## ONE DIMENSIONAL ARRAY

One dimensional arrays, are arrays with minimum of two elements in it in a single row.

In [27]:
I = np.array([1, 1, 2, 3, 5, 8, 13, 21]) # Fibonnacci series
J = np.array([4.4, 6.6, 8.8, 10.1, 12.12])

print("The dimension of I array is ",np.ndim(I))
print("The dimension of J array is ",np.ndim(J))

print("The data type of I array is ",I.dtype)
print("The data type of J array is ",J.dtype)


The dimension of I array is  1
The dimension of J array is  1
The data type of I array is  int32
The data type of J array is  float64


## Two-dimensional arrays
Two-dimensional arrays have more than one row and more than one column.

In [28]:
studentdata = np.array([ ["Name", "Year", "Marks"], 
               ["Bela", 2014, 78.2],
                ["Joe", 1987, 59.1],
               ["Sugar", 1990, 70]])

print(studentdata)

print("Dimension of 'studentdata' :", np.ndim (studentdata))

[['Name' 'Year' 'Marks']
 ['Bela' '2014' '78.2']
 ['Joe' '1987' '59.1']
 ['Sugar' '1990' '70']]
Dimension of 'studentdata' : 2


Even though Year and Marks are not string type data, here by default they are considered as string type data. So we can't perform any mathematical operations on these values. In order to perform any calculations, we need to convert the data into integers or float type data.

That is where dataframe, which we will study in the next section is very useful. It is a powerful 2-d data structure that can convert the data type with ease and help us perform various operations. 

For example:

In [29]:
import pandas as pd

In [30]:
studentdata1 = pd.DataFrame(studentdata)

studentdata1.head()



0     1      2
0   Name  Year  Marks
1   Bela  2014   78.2
2    Joe  1987   59.1
3  Sugar  1990     70

In [31]:
data = pd.read_csv(r"C:\Users\ramsu\ltphd\banknifty_feb Future daily.csv")

data.head(1)

Ticker          Date/Time      Open      High      Low  \
0  BANKNIFTY20FEBFUT  20-01-02 00:00:00  32444.85  32711.15  32394.0   

      Close  Volume  
0  32685.85   25920

In [32]:
array_data = np.array(data)

print("Dimensions of the data frame is: ",np.ndim(array_data))
print("Data type of the data frame is: ",array_data.dtype)

Dimensions of the data frame is:  2
Data type of the data frame is:  object


In [33]:
np.mean(data["Volume"])


1655735.3846153845

In [34]:
data.Volume.mean()

1655735.3846153845

In [35]:
data.Volume.rolling(window=5).mean()

0           NaN
1           NaN
2           NaN
3           NaN
4       52064.0
5       59824.0
6       62020.0
7       55512.0
8       52288.0
9       49328.0
10      47768.0
11      54536.0
12      68732.0
13      82972.0
14     112324.0
15     148124.0
16     177956.0
17     245200.0
18     342288.0
19     447008.0
20     717596.0
21    1510740.0
22    2589356.0
23    3306628.0
24    4040244.0
25    4457352.0
26    4484712.0
27    3883672.0
28    3496032.0
29    3115512.0
30    2824332.0
31    2444752.0
32    2687748.0
33    2754068.0
34    2900044.0
35    3013524.0
36    3151108.0
37    2967768.0
38    2842864.0
Name: Volume, dtype: float64

In [36]:
# A 3D array is an 'array of arrays'. Have a quick look at it 

b = np.array([ [[111, 222], [333, 444]],
               [[121, 212], [221, 222]],
               [[555, 560], [565, 570]] ])

print(b)
print("Dimension of 'b' :", np.ndim (b))

# In this array, there are three, 2-D arrays

[[[111 222]
  [333 444]]

 [[121 212]
  [221 222]]

 [[555 560]
  [565 570]]]
Dimension of 'b' : 3


## The shape of an array

**What it is:** The shape of an array returns the number of rows (axis = 0) and the number of columns (axis = 1)

**Why is it important to understand:** It helps you to understand the number of rows and columns in an array 

**How is it different from Dimensions:** It is not that different from dimensions, just that functions called are different. 

In [37]:
a1 = np.array([ [11, 22, 33],
               [12, 24, 36],
               [13, 26, 39],
               [14, 28, 42],
               [15, 30, 45],
               [16, 32, 48]])

print (a1)
np.shape(a1)

[[11 22 33]
 [12 24 36]
 [13 26 39]
 [14 28 42]
 [15 30 45]
 [16 32 48]]


(6, 3)

### We can also change the shape of an array

In [38]:
a1.shape = (9,2)
print (a1)

[[11 22]
 [33 12]
 [24 36]
 [13 26]
 [39 14]
 [28 42]
 [15 30]
 [45 16]
 [32 48]]


    You might have guessed by now that the new shape must correspond to the number of elements of the array, i.e. the total size of the new array must be the same as the old one. We will raise an exception if this is not the case.

In [39]:
# Shape of a 1 dimension array or scalar

a = np.array(165416113)
print(np.shape(a))


()


In [40]:
my_array = np.array([[10, 20, 30],[11, 22, 33],[12, 24, 36]])
print (my_array)
print(type(my_array))


[[10 20 30]
 [11 22 33]
 [12 24 36]]
<class 'numpy.ndarray'>


In [41]:
#Type your code in line 6
my_array_shape = np.shape(my_array)
print (my_array_shape)

(3, 3)
